# package: DragNDrop

set(CPACK_BUNDLE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_BUNDLE_ICON "${CMAKE_SOURCE_DIR}/src/vhf/icons/vhf-main.ico")

if(DEFINED PACKAGE_SYSTEM_DISTRIBUTION)
	message(STATUS "System Distribution: ${PACKAGE_SYSTEM_DISTRIBUTION}")
	set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${PACKAGE_SYSTEM_DISTRIBUTION}")
endif()

